### ISSUE TITLE
Problem with On the Fly Projections

### ISSUE THREAD

**Issue by jorgealmerio** [mach0/qchainage#11]
First of all,

Thank you for the Plugin!!!

Issue: When On the fly project option is enabled I got innaccurate measures.

**Comment by mach0** [comment]
Hi and thanks for your report.
Currently I do not have time to investigate the problems with OTF on - so I just added a warning for now if OTF is enabled. It should work if you disable otf - do the chainage on the lines you want to chain - and enable otf again.

**Comment by mach0** [comment]
Solved with e41cf8d433 as with QGIS3 OTF will always be enabled and the chainage will now always be in the projection of the layer to chainage using the new introduced QgsUnitTypes
