### ISSUE TITLE
the plugin crashed in QGis 2.14.2 Essen

### ISSUE THREAD

**Issue by MannusEtten** [mach0/qchainage#12]
unfortunately, when i select my line and use the plugin QGis crashes.
so maybe you know how it comes, but how can i read the dump file?

i will fork the code and maybe I can debug the plugin

**Comment by mach0** [comment]
Hi! Could you probably make the problematic file available? I tried it several times but so far I had no crash - which kind of provider do you use? Shapefile? Spatialite? PostGIS? A sample would be really helpful.

**Comment by newemi** [comment]
Hi

I use shapefile. my version Qgis 2.10.1 Pisa

Emilio Bizzarri



----Messaggio originale----

Da: notifications@github.com

Data: 18-mag-2016 9.00

A: "mach0/qchainage"<qchainage@noreply.github.com>

Ogg: Re: [mach0/qchainage] the plugin crashed in QGis 2.14.2 Essen (#12)




Hi! Could you probably make the problematic file available? I tried it several times but so far I had no crash - which kind of provider do you use? Shapefile? Spatialite? PostGIS? A sample would be really helpful.

**Comment by MannusEtten** [comment]
at home on my 2.12 version of QGIS it works but the distances are in planar instead of geodesic. So 100 km is not 100 km :-(

I am working now on a C#-app to implement the same functionality
