### ISSUE TITLE
python error at start up plugin QGIS 3.0.3 

### ISSUE THREAD

**Issue by pigreco** [mach0/qchainage#14]
the plugin is installed without problems, but pyton error appears at startup

![image](https://user-images.githubusercontent.com/7631137/41622195-20bc9930-740f-11e8-80db-0d33bed7209f.png)

error:
2018-06-19T22:18:53	WARNING	Traceback (most recent call last):
			  File "C:/Users/Salvatore/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qchainage\qchainagedialog.py", line 95, in on_selectLayerComboBox_currentIndexChanged
			    self.da.setSourceCrs(layer.crs())
			TypeError: QgsDistanceArea.setSourceCrs(): not enough arguments

win 10 64 bit
OSGeo4w QGIS 3.0.3

8a899c8758

THANK YOU

**Comment by mach0** [comment]
Thanks for your report, I am already aware of this (thus it is still marked as experimental) but currently lack of time to fix it - I hope there will be a stable version soon available for QGIS 3

**Comment by mach0** [comment]
That should be done with the released version as of today (thought I've spotted some other small bugs already)
