### ISSUE TITLE
Qchainage not starting at the end of poly line 

### ISSUE THREAD

**Issue by nbombers** [mach0/qchainage#16]
I'm trying to calculate a 10m chainage on a layer single part polylines I have in QGIS but when I use the plugin the chainage starts at mid point on the lines. It appears as if it's selecting random vertices to start and begin the chainage
![qchain](https://user-images.githubusercontent.com/44692685/47895659-b912c380-debd-11e8-9b98-a20b4151a847.JPG)

**Comment by mach0** [comment]
Hi and thanks for the report.
Is the polyline available somewhere? 
I had such cases too, but only with polylines that were merged with one part going in the "wrong" direction. So before merging the polyline every line should point in the same direction.

**Comment by nbombers** [comment]
@mach0 thanks for the info, I've gone back to the segments that were merged into the polylines and noted that some of them are going in opposite directions (right at the location of the chainage errors) we'll have to sort that out.

**Comment by mach0** [comment]
@nbombers let me know if everything works afterwards (and yes I know I should update the plugin, but I'm missing the time) ;)

**Comment by nbombers** [comment]
@mach0 unfortunately still having the same issue - even after rectifying the segment directions. The plugin seems to be using the 1st vertex in the dissolved layer which is not necessarily the first in the polyline
![qchain](https://user-images.githubusercontent.com/44692685/48045689-7e729900-e1e5-11e8-8b6e-4d842f3e1ba0.JPG)

**Comment by mach0** [comment]
Hi! Do you have a sample for me to investigate?
Is it possible that it might be something like this:
https://gis.stackexchange.com/questions/271341/cleanly-splitting-polylines-reordering-vertices-in-qgis

**Comment by mach0** [comment]
could you already solve this?

**Comment by nbombers** [comment]
hi @mach0 we pulled our chainage from our roads database and overlaid that on the lines. We never resolved the issue with the vertices

**Comment by mach0** [comment]
@nbombers thanks for your reply. Can you provide a sample line for me so that I can probably look at the problem?

**Comment by mach0** [comment]
closing as the issue seems with the data
