### ISSUE TITLE
QChainage - is possible to exceed the limit of the 99 parts ?

### ISSUE THREAD

**Issue by newemi** [mach0/qchainage#8]
I would want to know if it is possible to exceed the limit of the 99
parts of equal length in which it is possible to divide in equal parts
a polilinea.
In the Decimal Metric System them it is important to catch up the value
of 100, 1000 or 10000 equal parts.
For a line of street distance a subdivision in equal parts would be had
(every 10 meters or 5 meters) along a section of 1 km or multiples of
km.
I must necessarily divide a street distance between two marks them of
progressive kilometric es. between km 710 and km 711, or between km
710 and km 720
thanks

**Comment by mach0** [comment]
Hi,
just took a short look - it is an easy fix - will probably prepare a new release in the evening or tomorrow evening .. thanks for the issue

**Comment by newemi** [comment]
Buonasera, 

Thanks a lot, I have tried the operation of the refresh of the plugin and works to the large one.
