### ISSUE TITLE
determine drawing direction

### ISSUE THREAD

**Issue by MannusEtten** [mach0/qchainage#9]
how does qchainage decide where to start?

i have one feature and want to put the milestones from west to east but QChainage place them from east to west

**Comment by mach0** [comment]
Hi! It follows how the feature has been entered. You can change a feature (line) direction:
http://gis.stackexchange.com/questions/9261/how-can-i-switch-line-direction-in-qgis
Good suggestion to possibly do it in the plugin, but currently I do not have the time to do it.

**Comment by mach0** [comment]
if there will be an easy way to orient lines in the same direction I will take a look.
For now the lines just have to be prepared with the correct tools do orient them beforehand
